logging:
  level:
    org.springframework.web.servlet.DispatcherServlet : debug
    org.apache.tomcat.util.http.Parameters: debug
    io.swagger.models.parameters.AbstractSerializableParameter: error
    com.jt.baimo.baimolinggong.mapper: debug
    com.jt.baimo.baimolinggong.other: debug


